#version: '3'

services:

  plex-mount:
    #image: pknw1/pfs:final
    build: .
    container_name: plex-mount
    restart: always
    hostname: plex-mount
    privileged: true
    dns:
      - 8.8.8.8
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp:/tmp
      - ./config/plex-mount/config.json:/app/config.json
      - ./mount:/mnt:shared
    environment:
      - TZ=Europe/London
      - VIRTUAL_HOST=plex-mount.pknw1.co.uk
      - VIRTUAL_PORT=80
      - PUID=666
      - PGID=666


networks:
  proxy:
    external:
      name: proxy

